import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Shield, CheckCircle2, AlertTriangle, Target, Leaf, Download } from "lucide-react";
import jsPDF from "jspdf";
import { format } from "date-fns";
import { useAuth } from "@/hooks/useAuth";

const EPRCompliancePanel = () => {
  const { profile } = useAuth();

  const { data: collections } = useQuery({
    queryKey: ["corp_epr_collections"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("collections")
        .select("*, material_types(name, unit)")
        .order("collected_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  const totalKg = collections?.reduce((s, c) => s + Number(c.quantity), 0) || 0;
  const plasticKg = collections?.filter((c) => {
    const name = ((c as any).material_types?.name || "").toLowerCase();
    return name.includes("pet") || name.includes("hdpe") || name.includes("plastic");
  }).reduce((s, c) => s + Number(c.quantity), 0) || 0;

  // EPR targets (configurable per company)
  const annualTarget = 5000; // kg
  const quarterlyTarget = annualTarget / 4;
  const annualProgress = Math.min((plasticKg / annualTarget) * 100, 100);
  const quarterlyProgress = Math.min((plasticKg / quarterlyTarget) * 100, 100);

  const checks = [
    { label: "EPR Scheme Registration", pass: true, detail: "Registered with KEPRO" },
    { label: "Annual Plastic Offset Target", pass: annualProgress >= 100, detail: `${plasticKg.toFixed(0)} / ${annualTarget} kg (${annualProgress.toFixed(0)}%)` },
    { label: "Quarterly Reporting", pass: quarterlyProgress >= 100, detail: `Q1 target: ${quarterlyTarget} kg` },
    { label: "Audit Documentation", pass: !!profile?.company_registration, detail: profile?.company_registration ? `Reg: ${profile.company_registration}` : "Upload registration" },
    { label: "Waste Collection Partner Verified", pass: true, detail: "Duara Flow verified supply chain" },
  ];

  const score = (checks.filter((c) => c.pass).length / checks.length) * 100;

  const downloadEPRReceipt = () => {
    const doc = new jsPDF();
    const today = format(new Date(), "MMM d, yyyy");
    const receiptNo = `EPR-${Date.now().toString(36).toUpperCase()}`;

    doc.setFontSize(20);
    doc.text("Duara Flow", 20, 22);
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("EPR Compliance Receipt", 20, 32);
    doc.setTextColor(0);

    doc.setFontSize(10);
    doc.text(`Receipt #: ${receiptNo}`, 20, 46);
    doc.text(`Date: ${today}`, 20, 53);
    doc.text(`Company: ${profile?.full_name || "Corporate"}`, 20, 60);
    if (profile?.company_registration) doc.text(`Reg: ${profile.company_registration}`, 20, 67);

    doc.setFontSize(14);
    doc.text("Compliance Summary", 20, 84);
    doc.setFontSize(10);
    doc.text(`Total Plastic Offset: ${plasticKg.toFixed(1)} kg`, 25, 96);
    doc.text(`Annual Target: ${annualTarget} kg`, 25, 104);
    doc.text(`Progress: ${annualProgress.toFixed(1)}%`, 25, 112);
    doc.text(`Compliance Score: ${score.toFixed(0)}%`, 25, 120);

    let y = 136;
    doc.setFontSize(12);
    doc.text("Checklist", 20, y);
    y += 10;
    checks.forEach((c) => {
      doc.setFontSize(9);
      doc.text(`${c.pass ? "✓" : "✗"} ${c.label}: ${c.detail}`, 25, y);
      y += 8;
    });

    doc.setFontSize(7);
    doc.setTextColor(130);
    doc.text("This EPR compliance receipt is system-generated by Duara Flow and verifiable via QR code.", 20, 275);
    doc.text(`Document ID: ${receiptNo} | Generated: ${today}`, 20, 281);
    doc.save(`epr-receipt-${receiptNo}.pdf`);
  };

  return (
    <div className="space-y-6">
      <Card className="shadow-soft">
        <CardContent className="p-5">
          <div className="flex items-center gap-3 mb-4">
            <Shield className="w-8 h-8 text-primary" />
            <div className="flex-1">
              <p className="text-lg font-semibold text-foreground">EPR Compliance Score</p>
              <p className="text-xs text-muted-foreground">Extended Producer Responsibility tracking</p>
            </div>
            <Button size="sm" onClick={downloadEPRReceipt}>
              <Download className="w-4 h-4 mr-1" /> Receipt
            </Button>
          </div>
          <div className="flex items-center gap-4">
            <Progress value={score} className="flex-1 h-3" />
            <span className="text-lg font-bold text-primary">{score.toFixed(0)}%</span>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="shadow-soft">
          <CardContent className="p-4 text-center">
            <Target className="w-7 h-7 text-primary mx-auto mb-2" />
            <p className="text-xl font-bold text-foreground">{annualProgress.toFixed(0)}%</p>
            <p className="text-xs text-muted-foreground">Annual Target</p>
          </CardContent>
        </Card>
        <Card className="shadow-soft">
          <CardContent className="p-4 text-center">
            <Leaf className="w-7 h-7 text-primary mx-auto mb-2" />
            <p className="text-xl font-bold text-foreground">{plasticKg.toFixed(0)} kg</p>
            <p className="text-xs text-muted-foreground">Plastic Offset</p>
          </CardContent>
        </Card>
        <Card className="shadow-soft">
          <CardContent className="p-4 text-center">
            <Shield className="w-7 h-7 text-accent mx-auto mb-2" />
            <p className="text-xl font-bold text-foreground">{totalKg.toFixed(0)} kg</p>
            <p className="text-xs text-muted-foreground">Total Diverted</p>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-soft">
        <CardHeader><CardTitle className="text-lg">Compliance Checklist</CardTitle></CardHeader>
        <CardContent className="space-y-3">
          {checks.map((c, i) => (
            <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-muted/30 border border-border">
              {c.pass ? <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" /> : <AlertTriangle className="w-5 h-5 text-accent shrink-0 mt-0.5" />}
              <div className="flex-1">
                <p className="text-sm font-medium text-foreground">{c.label}</p>
                <p className="text-xs text-muted-foreground">{c.detail}</p>
              </div>
              <Badge variant={c.pass ? "default" : "secondary"}>{c.pass ? "Pass" : "Action"}</Badge>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
};

export default EPRCompliancePanel;
