import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, FileText, Truck } from "lucide-react";
import { format } from "date-fns";
import jsPDF from "jspdf";

const InvoicesPanel = () => {
  const { user, profile } = useAuth();

  const { data: collections } = useQuery({
    queryKey: ["aggregator_invoice_data", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("collections")
        .select("*, material_types(name, unit, price_per_unit)")
        .order("collected_at", { ascending: false });
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });

  const generateInvoice = () => {
    if (!collections?.length) return;
    const doc = new jsPDF();
    const today = format(new Date(), "MMM d, yyyy");
    const invoiceNo = `INV-${Date.now().toString(36).toUpperCase()}`;

    doc.setFontSize(20);
    doc.text("Duara Flow", 20, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Sales Invoice", 20, 30);
    doc.setTextColor(0);

    doc.text(`Invoice #: ${invoiceNo}`, 20, 44);
    doc.text(`Date: ${today}`, 20, 51);
    doc.text(`From: ${profile?.full_name || "Aggregator"}`, 20, 58);
    if (profile?.phone_number) doc.text(`Phone: ${profile.phone_number}`, 20, 65);

    // Aggregate materials
    const materialMap = new Map<string, { name: string; qty: number; price: number; unit: string }>();
    collections.forEach((c) => {
      const mt = (c as any).material_types;
      const key = c.material_type_id;
      const existing = materialMap.get(key);
      if (existing) {
        existing.qty += Number(c.quantity);
      } else {
        materialMap.set(key, {
          name: mt?.name || "Unknown",
          qty: Number(c.quantity),
          price: Number(mt?.price_per_unit || 0),
          unit: mt?.unit || "kg",
        });
      }
    });

    let y = 80;
    doc.setFillColor(34, 87, 62);
    doc.rect(20, y - 5, 170, 8, "F");
    doc.setTextColor(255);
    doc.setFontSize(9);
    doc.text("Material", 22, y);
    doc.text("Quantity", 85, y);
    doc.text("Unit Price", 120, y);
    doc.text("Total (KES)", 155, y);
    doc.setTextColor(0);

    let grandTotal = 0;
    y += 10;
    materialMap.forEach((m) => {
      const total = m.qty * m.price;
      grandTotal += total;
      doc.text(m.name, 22, y);
      doc.text(`${m.qty.toFixed(1)} ${m.unit}`, 85, y);
      doc.text(m.price.toFixed(2), 120, y);
      doc.text(total.toLocaleString(), 155, y);
      y += 8;
    });

    y += 4;
    doc.line(20, y - 3, 190, y - 3);
    doc.setFontSize(12);
    doc.text(`Grand Total: KES ${grandTotal.toLocaleString()}`, 110, y + 5);

    doc.setFontSize(7);
    doc.setTextColor(130);
    doc.text("This invoice is system-generated by Duara Flow.", 20, 280);
    doc.save(`invoice-${invoiceNo}.pdf`);
  };

  const generateDeliveryNote = () => {
    if (!collections?.length) return;
    const doc = new jsPDF();
    const today = format(new Date(), "MMM d, yyyy");
    const noteNo = `DN-${Date.now().toString(36).toUpperCase()}`;

    doc.setFontSize(20);
    doc.text("Duara Flow", 20, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Delivery Note", 20, 30);
    doc.setTextColor(0);

    doc.text(`Note #: ${noteNo}`, 20, 44);
    doc.text(`Date: ${today}`, 20, 51);
    doc.text(`Delivered by: ${profile?.full_name || "Aggregator"}`, 20, 58);

    let y = 74;
    doc.setFillColor(34, 87, 62);
    doc.rect(20, y - 5, 170, 8, "F");
    doc.setTextColor(255);
    doc.setFontSize(9);
    doc.text("Batch ID", 22, y);
    doc.text("Material", 70, y);
    doc.text("Quantity", 120, y);
    doc.text("Date", 155, y);
    doc.setTextColor(0);

    y += 10;
    collections.slice(0, 30).forEach((c) => {
      if (y > 270) { doc.addPage(); y = 20; }
      const mt = (c as any).material_types;
      doc.setFontSize(8);
      doc.text(c.batch_id, 22, y);
      doc.text(mt?.name || "—", 70, y);
      doc.text(`${Number(c.quantity).toFixed(1)} ${mt?.unit || "kg"}`, 120, y);
      doc.text(format(new Date(c.collected_at), "MMM d"), 155, y);
      y += 7;
    });

    doc.setFontSize(9);
    y += 8;
    doc.text("Received by: ____________________________", 20, y);
    y += 12;
    doc.text("Signature: ____________________________", 20, y);
    y += 12;
    doc.text("Date: ____________________________", 20, y);

    doc.setFontSize(7);
    doc.setTextColor(130);
    doc.text("System-generated delivery note — Duara Flow", 20, 285);
    doc.save(`delivery-note-${noteNo}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Card className="shadow-soft">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center gap-3">
              <FileText className="w-6 h-6 text-primary" />
              <div>
                <p className="text-sm font-medium text-foreground">Sales Invoice</p>
                <p className="text-xs text-muted-foreground">Generate a professional invoice summarizing all collected materials and their value</p>
              </div>
            </div>
            <Button size="sm" onClick={generateInvoice} disabled={!collections?.length} className="w-full">
              <Download className="w-4 h-4 mr-1" /> Generate Invoice
            </Button>
          </CardContent>
        </Card>

        <Card className="shadow-soft">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center gap-3">
              <Truck className="w-6 h-6 text-primary" />
              <div>
                <p className="text-sm font-medium text-foreground">Delivery Note</p>
                <p className="text-xs text-muted-foreground">Generate a delivery note with batch details and signature fields</p>
              </div>
            </div>
            <Button size="sm" variant="outline" onClick={generateDeliveryNote} disabled={!collections?.length} className="w-full">
              <Download className="w-4 h-4 mr-1" /> Generate Note
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Recent collections for reference */}
      <Card className="shadow-soft">
        <CardHeader><CardTitle className="text-lg">Recent Collections</CardTitle></CardHeader>
        <CardContent>
          {!collections?.length ? (
            <p className="text-sm text-muted-foreground">No collection data for documents.</p>
          ) : (
            <div className="divide-y divide-border">
              {collections.slice(0, 10).map((c) => {
                const mt = (c as any).material_types;
                return (
                  <div key={c.id} className="flex items-center justify-between py-2.5">
                    <div>
                      <p className="text-sm font-medium text-foreground">{mt?.name}</p>
                      <p className="text-xs text-muted-foreground font-mono">{c.batch_id}</p>
                    </div>
                    <p className="text-sm text-foreground">{Number(c.quantity).toFixed(1)} {mt?.unit}</p>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default InvoicesPanel;
