import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Loader2, DollarSign, Download, Smartphone, FileText } from "lucide-react";
import { format } from "date-fns";
import jsPDF from "jspdf";

const EarningsPanel = () => {
  const { user, profile } = useAuth();

  const { data: collections } = useQuery({
    queryKey: ["collections_earnings", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("collections")
        .select("*, material_types(name, unit, price_per_unit)")
        .eq("user_id", user!.id)
        .order("collected_at", { ascending: false });
      if (error) throw error;
      return data;
    },
    enabled: !!user?.id,
  });

  const { data: payments, isLoading: paymentsLoading } = useQuery({
    queryKey: ["payments", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("payments")
        .select("*")
        .eq("user_id", user!.id)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
    enabled: !!user?.id,
  });

  const totalEarnings = collections?.reduce((sum, c) => {
    const price = Number((c as any).material_types?.price_per_unit || 0);
    return sum + Number(c.quantity) * price;
  }, 0) || 0;

  const totalPaid = payments?.filter(p => p.status === "completed").reduce((sum, p) => sum + Number(p.amount), 0) || 0;

  const downloadReceipt = (payment: any) => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Duara Flow - Payment Receipt", 20, 25);
    doc.setFontSize(11);
    doc.text(`Receipt #: ${payment.mpesa_receipt_number || payment.id.slice(0, 8)}`, 20, 40);
    doc.text(`Date: ${format(new Date(payment.created_at), "MMM d, yyyy h:mm a")}`, 20, 48);
    doc.text(`Amount: KES ${Number(payment.amount).toFixed(2)}`, 20, 56);
    doc.text(`Phone: ${payment.phone_number}`, 20, 64);
    doc.text(`Status: ${payment.status}`, 20, 72);
    if (payment.description) doc.text(`Description: ${payment.description}`, 20, 80);
    doc.setFontSize(9);
    doc.text("This is a system-generated receipt from Duara Flow.", 20, 100);
    doc.save(`receipt-${payment.id.slice(0, 8)}.pdf`);
  };

  const downloadQuotation = () => {
    if (!collections?.length) return;
    const doc = new jsPDF();
    const today = format(new Date(), "MMM d, yyyy");
    const quoteId = `Q-${Date.now().toString(36).toUpperCase()}`;

    // Header
    doc.setFontSize(20);
    doc.text("Duara Flow", 20, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Waste Collection Quotation", 20, 30);
    doc.setTextColor(0);

    // Meta
    doc.setFontSize(10);
    doc.text(`Quotation #: ${quoteId}`, 20, 44);
    doc.text(`Date: ${today}`, 20, 51);
    doc.text(`Prepared for: ${profile?.full_name || "Waste Picker"}`, 20, 58);
    if (profile?.phone_number) doc.text(`Phone: ${profile.phone_number}`, 20, 65);

    // Table header
    let y = 80;
    doc.setFillColor(34, 87, 62);
    doc.rect(20, y - 5, 170, 8, "F");
    doc.setTextColor(255);
    doc.setFontSize(9);
    doc.text("Material", 22, y);
    doc.text("Qty", 90, y);
    doc.text("Unit Price (KES)", 115, y);
    doc.text("Total (KES)", 160, y);
    doc.setTextColor(0);

    // Aggregate by material
    const materialMap = new Map<string, { name: string; qty: number; price: number; unit: string }>();
    collections.forEach((c) => {
      const mt = (c as any).material_types;
      const key = c.material_type_id;
      const existing = materialMap.get(key);
      if (existing) {
        existing.qty += Number(c.quantity);
      } else {
        materialMap.set(key, {
          name: mt?.name || "Unknown",
          qty: Number(c.quantity),
          price: Number(mt?.price_per_unit || 0),
          unit: mt?.unit || "kg",
        });
      }
    });

    let grandTotal = 0;
    y += 10;
    doc.setFontSize(9);
    materialMap.forEach((m) => {
      const lineTotal = m.qty * m.price;
      grandTotal += lineTotal;
      doc.text(m.name, 22, y);
      doc.text(`${m.qty.toFixed(1)} ${m.unit}`, 90, y);
      doc.text(m.price.toFixed(2), 115, y);
      doc.text(lineTotal.toFixed(2), 160, y);
      y += 8;
    });

    // Total
    y += 4;
    doc.setDrawColor(200);
    doc.line(20, y - 3, 190, y - 3);
    doc.setFontSize(11);
    doc.text(`Grand Total: KES ${grandTotal.toFixed(2)}`, 120, y + 4);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text("This quotation is system-generated by Duara Flow and is valid for 7 days.", 20, 270);
    doc.text(`Generated on ${today}`, 20, 276);

    doc.save(`quotation-${quoteId}.pdf`);
  };

  return (
    <div className="space-y-6">
      {/* Summary cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="shadow-soft">
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-wider">Total Earned</p>
            <p className="text-2xl font-display font-bold text-primary">KES {totalEarnings.toFixed(0)}</p>
          </CardContent>
        </Card>
        <Card className="shadow-soft">
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-wider">Total Paid Out</p>
            <p className="text-2xl font-display font-bold text-foreground">KES {totalPaid.toFixed(0)}</p>
          </CardContent>
        </Card>
        <Card className="shadow-soft">
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-wider">Balance</p>
            <p className="text-2xl font-display font-bold text-gold">KES {(totalEarnings - totalPaid).toFixed(0)}</p>
          </CardContent>
        </Card>
      </div>

      {/* Quotation download */}
      <Card className="shadow-soft">
        <CardContent className="flex items-center justify-between p-4">
          <div className="flex items-center gap-3">
            <FileText className="w-5 h-5 text-primary" />
            <div>
              <p className="text-sm font-medium text-foreground">Collection Quotation</p>
              <p className="text-xs text-muted-foreground">Download a summary PDF of all your collected materials &amp; value</p>
            </div>
          </div>
          <Button size="sm" variant="outline" onClick={downloadQuotation} disabled={!collections?.length}>
            <Download className="w-4 h-4 mr-1" /> Download
          </Button>
        </CardContent>
      </Card>

      {/* Payment history */}
      <Card className="shadow-soft">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-base">M-Pesa Payment History</CardTitle>
            <Smartphone className="w-5 h-5 text-primary" />
          </div>
        </CardHeader>
        <CardContent>
          {paymentsLoading ? (
            <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>
          ) : !payments?.length ? (
            <div className="text-center py-8 text-muted-foreground">
              <DollarSign className="w-10 h-10 mx-auto mb-2 opacity-40" />
              <p className="text-sm">No payments yet.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {payments.map(p => (
                <div key={p.id} className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
                  <div>
                    <p className="text-sm font-medium">KES {Number(p.amount).toFixed(2)}</p>
                    <p className="text-xs text-muted-foreground">
                      {format(new Date(p.created_at), "MMM d, yyyy • h:mm a")} • {p.phone_number}
                    </p>
                    {p.mpesa_receipt_number && (
                      <p className="text-xs text-muted-foreground">Ref: {p.mpesa_receipt_number}</p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant={p.status === "completed" ? "default" : p.status === "failed" ? "destructive" : "secondary"}>
                      {p.status}
                    </Badge>
                    <Button variant="ghost" size="icon" onClick={() => downloadReceipt(p)} title="Download receipt">
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default EarningsPanel;
